# Generated by Django 2.2.12 on 2020-06-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_id',
            new_name='author',
        ),
    ]
